"""First-install local Elasticsearch 8 with TLS; no existing node is modified."""
import base64
import getpass
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import ssl
import subprocess
import tempfile
import time
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen, build_opener, HTTPSHandler, ProxyHandler
import zipfile

ES = Path('/etc/elasticsearch')
ETC = Path('/etc/ibatyr-apm')
BIN = Path('/usr/share/elasticsearch/bin')
FINGERPRINT = '46095ACC8548582C1A2699A9D27D666CD88E42B4'


def run(*args, **kwargs):
    return subprocess.run([str(x) for x in args], check=True, **kwargs)


def write(path, content, mode=0o600):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
    with os.fdopen(fd, 'w') as stream:
        stream.write(content)


def configuration():
    return '''cluster.name: ibatyr-apm
node.name: ibatyr-storage-1
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 127.0.0.1
http.port: 9200
transport.port: 9300
discovery.type: single-node
xpack.security.enabled: true
xpack.security.autoconfiguration.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl:
  enabled: true
  key: ibatyr-certs/node.key
  certificate: ibatyr-certs/node.crt
  certificate_authorities: ["ibatyr-certs/ca.crt"]
xpack.security.transport.ssl:
  enabled: true
  verification_mode: full
  key: ibatyr-certs/node.key
  certificate: ibatyr-certs/node.crt
  certificate_authorities: ["ibatyr-certs/ca.crt"]
'''


def validate(version, heap):
    if not re.fullmatch(r'8\.\d+\.\d+', version):
        raise RuntimeError('Укажите точную версию Elasticsearch 8.x.y')
    if not 1 <= heap <= 16:
        raise RuntimeError('heap-gb должен быть от 1 до 16')


def install(a, free):
    validate(a.version, a.heap_gb)
    if ES.exists() or Path('/var/lib/elasticsearch').exists() or (ETC/'storage.json').exists():
        raise RuntimeError('Elasticsearch/его данные уже существуют; first-install не изменяет их')
    if shutil.which('dpkg-query'):
        p = subprocess.run(['dpkg-query', '-W', '-f=${Status}', 'elasticsearch'], capture_output=True, text=True)
        if 'installed' in p.stdout:
            raise RuntimeError('Пакет Elasticsearch уже установлен')
    free(9200); free(9300)
    mem = int(next(l.split()[1] for l in Path('/proc/meminfo').read_text().splitlines() if l.startswith('MemTotal:'))) // 1024
    if mem < (a.heap_gb*2+4)*1024:
        raise RuntimeError('Недостаточно RAM: нужно минимум 2×heap + 4 GiB для совместной VM')
    if shutil.disk_usage('/var/lib').free < 20*1024**3:
        raise RuntimeError('Нужно минимум 20 GiB свободного диска; sizing retention выполняется отдельно')
    for folder in [Path('/etc/apt/sources.list.d')]:
        if any('artifacts.elastic.co/packages' in p.read_text(errors='ignore') for p in folder.iterdir() if p.is_file()):
            raise RuntimeError('Уже настроен Elastic APT repository; проверьте существующую установку')
    keyring = Path('/usr/share/keyrings/ibatyr-elastic.gpg')
    source = Path('/etc/apt/sources.list.d/ibatyr-elastic-8.list')
    sysctl = Path('/etc/sysctl.d/90-ibatyr-elasticsearch.conf')
    if any(p.exists() for p in (keyring, source, sysctl)):
        raise RuntimeError('Обнаружены файлы предыдущей попытки; см. docs/ELASTICSEARCH.md')
    run('apt-get', 'update')
    run('apt-get', 'install', '-y', 'ca-certificates', 'gnupg')
    with tempfile.TemporaryDirectory() as tmp:
        key = Path(tmp)/'elastic.asc'
        with urlopen('https://artifacts.elastic.co/GPG-KEY-elasticsearch', timeout=30) as response:
            key.write_bytes(response.read(100000))
        fingerprint = run('gpg', '--batch', '--with-colons', '--show-keys', key, capture_output=True, text=True).stdout
        if FINGERPRINT not in [line.split(':')[9] for line in fingerprint.splitlines() if line.startswith('fpr:')]:
            raise RuntimeError('Не совпал fingerprint ключа Elastic')
        run('gpg', '--batch', '--dearmor', '--output', keyring, key)
    keyring.chmod(0o644)
    write(source, 'deb [signed-by=/usr/share/keyrings/ibatyr-elastic.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main\n', 0o644)
    run('apt-get', 'update')
    # APT validates repository signatures; require the chosen version, never fall back to latest.
    run('systemctl', 'mask', 'elasticsearch.service')
    run('apt-get', 'install', '-y', 'elasticsearch='+a.version)
    run('systemctl', 'stop', 'elasticsearch')
    ETC.mkdir(mode=0o750, exist_ok=True)
    backup = ETC/'es-install-backup'; backup.mkdir(mode=0o700)
    shutil.copy2(ES/'elasticsearch.yml', backup/'elasticsearch.yml')
    # Remove only TLS passwords generated by the package; our PEM keys use file permissions.
    entries = run(BIN/'elasticsearch-keystore', 'list', capture_output=True, text=True).stdout.splitlines()
    for name in ('xpack.security.http.ssl.keystore.secure_password', 'xpack.security.transport.ssl.keystore.secure_password', 'xpack.security.transport.ssl.truststore.secure_password'):
        if name in entries: run(BIN/'elasticsearch-keystore', 'remove', name)
    certs = ES/'ibatyr-certs'; certs.mkdir(mode=0o750)
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        run(BIN/'elasticsearch-certutil', 'ca', '--silent', '--pem', '--out', tmp/'ca.zip')
        with zipfile.ZipFile(tmp/'ca.zip') as z:
            (tmp/'ca.crt').write_bytes(z.read('ca/ca.crt'))
            (tmp/'ca.key').write_bytes(z.read('ca/ca.key'))
        run(BIN/'elasticsearch-certutil', 'cert', '--silent', '--pem', '--name', 'node', '--dns', 'localhost', '--ip', '127.0.0.1', '--ca-cert', tmp/'ca.crt', '--ca-key', tmp/'ca.key', '--out', tmp/'node.zip')
        with zipfile.ZipFile(tmp/'node.zip') as z:
            for name in ('node.crt', 'node.key'): (certs/name).write_bytes(z.read('node/'+name))
        shutil.copy2(tmp/'ca.crt', certs/'ca.crt')
        shutil.copy2(tmp/'ca.key', backup/'ca.key'); (backup/'ca.key').chmod(0o600)
    for path in [certs, *certs.iterdir()]:
        shutil.chown(path, user='root', group='elasticsearch'); path.chmod(0o750 if path.is_dir() else 0o640)
    (ES/'elasticsearch.yml').write_text(configuration());shutil.chown(ES/'elasticsearch.yml', user='root', group='elasticsearch');(ES/'elasticsearch.yml').chmod(0o640)
    write(ES/'jvm.options.d/ibatyr.options', f'-Xms{a.heap_gb}g\n-Xmx{a.heap_gb}g\n', 0o644)
    current = int(Path('/proc/sys/vm/max_map_count').read_text())
    write(sysctl, f'vm.max_map_count={max(current,1048576)}\n', 0o644)
    run('sysctl', '-p', sysctl)
    run('systemctl', 'unmask', 'elasticsearch.service')
    run('systemctl', 'daemon-reload');run('systemctl', 'enable', '--now', 'elasticsearch')
    context = ssl.create_default_context(cafile=str(certs/'ca.crt'))
    opener = build_opener(ProxyHandler({}), HTTPSHandler(context=context))
    for _ in range(90):
        try:
            opener.open('https://127.0.0.1:9200', timeout=3).close()
            raise RuntimeError('Elasticsearch ответил без авторизации; проверьте security')
        except HTTPError as e:
            if e.code == 401: break
        except (URLError, TimeoutError): pass
        time.sleep(2)
    else: raise RuntimeError('Elasticsearch не прошёл TLS readiness; см. /var/log/elasticsearch')
    run('apt-mark', 'hold', 'elasticsearch')
    print('Elasticsearch запущен с HTTPS на localhost. Задайте пароль администратора.')
    run(BIN/'elasticsearch-reset-password', '-u', 'elastic', '-i')
    provision()


def api(path, user, password, body=None, missing_ok=False):
    context = ssl.create_default_context(cafile=str(ES/'ibatyr-certs/ca.crt'))
    opener = build_opener(ProxyHandler({}), HTTPSHandler(context=context))
    request = Request('https://127.0.0.1:9200'+path,
                      data=json.dumps(body).encode() if body is not None else None,
                      method='PUT' if body is not None else 'GET',
                      headers={'Authorization':'Basic '+base64.b64encode((user+':'+password).encode()).decode(), 'Content-Type':'application/json'})
    try:
        with opener.open(request, timeout=30) as r: return json.load(r)
    except HTTPError as e:
        if missing_ok and e.code == 404: return {}
        raise RuntimeError(f'Elasticsearch API HTTP {e.code}; проверьте пароль/права, секреты не выводятся') from None


def role():
    return {'cluster':['monitor','manage_index_templates'], 'indices':[{'names':['ibatyr_*'], 'privileges':['all'], 'allow_restricted_indices':False}]}


def provision():
    profile = ETC/'storage.json'
    if profile.exists(): raise RuntimeError('storage.json уже существует; учётная запись не перезаписывается')
    if not (ES/'ibatyr-certs/ca.crt').exists(): raise RuntimeError('Сначала install.py elasticsearch; для внешнего ES см. docs/SERVER.md')
    admin = getpass.getpass('Повторите пароль elastic для создания пользователя OAP: ')
    # A named, namespace-restricted user is used by OAP, never the elastic superuser.
    existing = api('/_security/user/ibatyr_oap', 'elastic', admin, missing_ok=True)
    if existing: raise RuntimeError('Пользователь ibatyr_oap уже существует; требуется ручная проверка')
    api('/_security/role/ibatyr_oap', 'elastic', admin, role())
    password = secrets.token_urlsafe(36)
    values = {'nodes':'127.0.0.1:9200','user':'ibatyr_oap','password':password,'namespace':'ibatyr','ca':str(ES/'ibatyr-certs/ca.crt')}
    # Persist recovery data before creating the user. Refuse reruns rather than lose the password.
    write(profile, json.dumps(values), 0o600)
    api('/_security/user/ibatyr_oap', 'elastic', admin, {'password':password,'roles':['ibatyr_oap'],'enabled':True})
    api('/_cluster/health', 'ibatyr_oap', password)
    print('Хранилище готово. Учётные данные: /etc/ibatyr-apm/storage.json (root, 0600).')
    print('Следующий шаг: sudo python3 install.py server --storage elasticsearch --local-elasticsearch')
